### ISSUE TITLE
Create a 404 error page

### ISSUE THREAD

**Issue by hypermystic** [hypermystic/bookit#17]

**Comment by Wavist** [comment]
I'll create a static one with html and css. Assign this to me

**Comment by hypermystic** [comment]
can you also add it to the index.js so that it will work correctly as expected in the react

**Comment by hypermystic** [comment]
assigning it to you

**Comment by Wavist** [comment]
I will try. Thanks

**Comment by hypermystic** [comment]
Yeah..thanks...

**Comment by Wavist** [comment]
I just sent a PR. Review

**Comment by hypermystic** [comment]
Closing this case as this was resolved in the PR #21 and #27
