### ISSUE TITLE
auto redirect to https://todo-7e79c.web.app/

### ISSUE THREAD

**Issue by vinhyenvodoi98** [hypermystic/bookit#19]
now when run project it auto redirect to https://todo-7e79c.web.app/ ( a deployed websize ) so can't check what i coded

**Comment by hypermystic** [comment]
Don't know much but the issue seems to be because of the env variables used in the firebaseConfig.js. Removing them and adding the firebase config values directly solves the issue.
So as a workaround you can use this method for testing.
The issue might be related to the CORS
